id: I22B339D7
ocr_import_info:
  timestamp: '2023-06-27T14:53:06.019207+00:00'
  batch_id: batch-2746
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-27 14:55:28.094971+00:00
last_modified: 2023-06-27 14:55:28.094976+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG10776
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG10776
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྤྱོད་བསྡུས་སྒྲོན་མེ། ༼དབུ་མེད།༽
  languages:
  - bo
  author: སློབ་དཔོན་འཕགས་པ་ལྷ།
statistics:
  ocr_word_mean_confidence_index: 0.9142478597012093
  ocr_word_median_confidence_index: 0.9778704
bases:
  I1KG10840:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10840
      total_pages: 128
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10840.txt
    statistics:
      ocr_word_median_confidence_index: 0.9778704
      ocr_word_mean_confidence_index: 0.9142478597012093
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
